teleop_twist_joy_node:
  ros__parameters:
    axis_linear.x: 1
    axis_linear.y: -1
    axis_linear.z: -1

    axis_angular.yaw: 3
    axis_angular.pitch: -1
    axis_angular.roll: -1

    scale_linear.x: 1.0
    scale_linear.y: 1.0
    scale_angular.yaw: 1.0
    scale_angular.pitch: 1.0
    scale_angular.roll: 1.0

    require_enable_button: true
    enable_button: 5
